### PR TITLE
Move dxclib one level up; string handling in DxilRuntimeReflection 

### PR DESCRIPTION
**Pull request by hekota**
Move dxclib one level up / out of dxc directory
Change DxilRuntimeReflection handling of strings to be platform independent
Remove unused member in DxilRuntimeData
Fix opt tool (not part of the regular build)

### CODE REVIEW

**Comment by hekota** [comment]
@ehsannas - we need to move dxclib library one directory up (windows build system quirk) and I am having trouble making it work on the Travis Linux builds. Can you please take a look?

**Comment by ehsannas** [comment]
Thanks for letting me know @hekota. Yes, I'll take a look right away.

**Comment by pow2clk** [comment]
I don't want to step on @ehsannas's toes, but I think I know broadly what's going on. I have seen issues like this crop up before and they likely will again, so perhaps a general explanation might help in the future. 

It's likely we're all aware by now that Linux linking is more sensitive to ordering than others, but the confusion here is likely why a change like this would have had any effect on the ordering. The answer is that, unless dependencies are clearly laid out in the cmake files, the ordering on the link command line will be essentially arbitrary, but really governed by some kind of alphabetization. The change of the directory likely changed this ordering, which disrupted the ordering that worked purely by happenstance.

From the build failure, I can see that dxclib should depend on `dxilcontainer` library at least and probably a few others. Sussing all the others out is usually an iterative process as added dependencies might have dependencies of their own, but in the end, it makes the build more robust.

I've tried to think of a way to tease out all these missing dependencies so they can all be fixed now and even detected when a new one is added, but I've not come up with anything yet.

**Comment by pow2clk** [comment]
Looking at this again, I realize that I was mistaken about the cause, but the solution is the same.

CMake files inherit characteristics from the cmake files in the directories above them. The LLVM libraries that dxc requires were listed in the `dxc/` directory cmake file which is no longer inherited. Some of those might be more than dxclib needs by itself, but copying the assignment to `LLVM_LINK_COMPONENTS` should be sufficient.

**Comment by hekota** [comment]
Thanks Greg! I'll give it a shot.

**Comment by ehsannas** [comment]
In this case, since `dxclib` has been moved up to `clang/tools`, it is now a "clang tool" _on its own_, so it needs to find the things it depends on under `llvm/lib` (including `dxilcontainer` among others). I have the fix coming up.

**Comment by ehsannas** [comment]
The cmake change LGTM! It should fix the Linux build. Thanks!

**Comment by hekota** [comment]
@ehsannas, @pow2clk - thank you for your suggestions!

**Pull request merged**
