### PR TITLE
Dxil 1.4 update + packed dot intrinsics and SV_ShadingRate

### PR DESCRIPTION
**Pull request by tex3d**
Update to DXIL 1.4 and Shader Model 6.4

Add dot2add and dot4add_*8packed intrinsics

Add SV_ShadingRate plus optional feature flag … 
- Move/fix flag collection based on signature properties to be computed
  per entry function (including for libraries)

### CODE REVIEW

**Comment by ehsannas** [comment]
This change seems to break the Linux build. Please consider patching it if the fix is trivial. Thanks!

**Comment by tex3d** [comment]
>           This change seems to break the Linux build. Please consider patching it if the fix is trivial. Thanks!

I'm not sure what the issue is.  It says The Travis CI build passed to me.  When I look into that, it looks like each individual build failed, but I can't figure out why, since it looks like it passed everything, then exits with return code 1 at the end.  But the overall result says passed.  I see a bunch of build warnings, but these appear to be unrelated to this change, and don't prevent the build.

**Comment by antiagainst** [comment]
It's a sanity check we added at the early stage of supporting non-Windows systems to make sure DXIL output from the command-line is good. The check is against binaries directly, so it's gonna break every time DXIL version updates. Not really needed right now, so I removed it.

**Comment by antiagainst** [comment]
The Travis CI is set up to allow all build jobs to fail: https://github.com/Microsoft/DirectXShaderCompiler/blob/master/.travis.yml#L36-L38.

So Travis CI will always return success no matter what.

We initially set up it this way because non-Windows support is experimental and we don't want to disturb Microsoft workflow too much. It was mainly for us to see how it goes and pay attention to non-Windows platform status so that we can fix it if something went wrong. From the experience of past few months, it seems it rarely breaks; maybe only on large changes. I'd happy to flip it as correctly showing the build status if you guys think that's fine.

**Comment by antiagainst** [comment]
Travis CI is happy now. :)

**Pull request merged**
