### PR TITLE
[please ignore] testing whether Travis has stopped working.

### PR DESCRIPTION
**Pull request by ehsannas**

### CODE REVIEW

**Comment by ehsannas** [comment]
uh oh... it looks like Travis is not running :-/

**Comment by ehsannas** [comment]
it hasn't run on https://github.com/microsoft/DirectXShaderCompiler/pull/3086 either... not sure why...

**Comment by ehsannas** [comment]
well, it seems to be running, but not posting its results here 🤔 

https://travis-ci.org/github/microsoft/DirectXShaderCompiler/builds/718831981

**Comment by ehsannas** [comment]
anyway.... I can close this PR now...

**Comment by ehsannas** [comment]
I guess it's not because of capitalization like we had before (https://github.com/microsoft/DirectXShaderCompiler/pull/2799)

**Comment by ehsannas** [comment]
@pow2clk any idea why Travis has stopped running?

**Comment by ehsannas** [comment]
rather: any idea why Travis has stopped reporting status to github?

**Comment by ehsannas** [comment]
doing this might fix it: https://github.com/travis-ci/travis-ci/issues/9440#issuecomment-378707440

(maybe Travis has lost github authentication privileges to post its results to Github)

**Comment by pow2clk** [comment]
I don't think I have the permissions to make these changes in our project. @hekota does I think. Maybe she can help out?

**Comment by pow2clk** [comment]
It looks like #3080 was the last PR to get a response from travis. #3086 failed to. I don't see anything in that period that might have caused this directly though.

**Comment by hekota** [comment]
I checked and I see TravisCI under my settings > applications > Authorized OAuth Apps and also when I clink on it it does have Organization access for microsoft.

**Comment by ehsannas** [comment]
Thanks for checking @hekota. I'll search more to see if there are any information online about how to fix it. If nothing else works, we'll have to reach out to Travis-CI directly.

**Pull request closed without merging**
