### PR TITLE
[spirv] external: Update SPIRV-Tools with shader_clock DCE

### PR DESCRIPTION
**Pull request by MarijnS95**
https://github.com/KhronosGroup/SPIRV-Tools/pull/4047 enabled DCE for
vk::ReadClock which we're using. Without this patch unused bindings for
atomic counters attached to buffers show up.

---

This change barely didn't make it in #3306 but we really want it now :). With this PR #3287 is actually fixed.

### CODE REVIEW

**Comment by ehsannas** [comment]
Thanks for posting this @MarijnS95 . I just posted PR#3365 which pushes SPIRV-Tools to the latest (Jan 19). I'll close this PR as this is a bit older. Thanks!

**Comment by MarijnS95** [comment]
@ehsannas This updates to the latest hash as of today, including the DCE fix from 6 weeks ago?

**Comment by MarijnS95** [comment]
Your PR includes only one extra commit, that landed about 2 hours after this PR was mdae.

**Comment by ehsannas** [comment]
lol! 😄  yeah, I just pulled the latest available SPIRV-Tools commit

**Pull request closed without merging**
