### PR TITLE
[SPIR-V] Add -fvk-bind-*-heap flag to DXC

### LINKED ISSUE #6913: [Feature Request] [SPIR-V] -fvk-bind-resource-heap
**Is your feature request related to a problem? Please describe.**
As mentioned in https://github.com/microsoft/DirectXShaderCompiler/pull/6650, there will be a follow-up PR to add -fvk-bind-resource-heap and -fvk-bind-sampler-heap.

We have been waiting for months for that PR, and it should not be too much work. Maybe it's forgotten ?

### PR DESCRIPTION
**Pull request by Keenuts**
Those flags allow the user to hardcode the binding ID for the heaps. This allow the user to either force heap aliasing, or simply have more control over the heaps.

Fixes #6913

### CODE REVIEW

**Review by s-perron — CHANGES_REQUESTED** [review]
The only part that seems missing that other resources that are automatically assigned resources should not use the fixed binding for the descriptor heaps:

```
// RUN: %dxc -T cs_6_6 -E main -fcgl %s -spirv -fvk-bind-resource-heap 0 0 -fvk-bind-counter-heap 1 0 | FileCheck %s

// CHECK-DAG: OpDecorate %a DescriptorSet 0
// CHECK-DAG: OpDecorate %a Binding 2
// CHECK-DAG: OpDecorate %counter_var_a DescriptorSet 0
// CHECK-DAG: OpDecorate %counter_var_a Binding 3
RWStructuredBuffer<uint> a; 

[numthreads(1, 1, 1)]
void main() {  
// CHECK-DAG: OpDecorate %ResourceDescriptorHeap DescriptorSet 0
// CHECK-DAG: OpDecorate %ResourceDescriptorHeap Binding 0
// CHECK-DAG: OpDecorate %counter_var_ResourceDescriptorHeap DescriptorSet 0
// CHECK-DAG: OpDecorate %counter_var_ResourceDescriptorHeap Binding 1
  RWStructuredBuffer<uint> b = ResourceDescriptorHeap[1];
  
  a.IncrementCounter();
  b.IncrementCounter();
}
```

**Comment by Keenuts** [comment]
> resources

You mean a test checking only resources related to the flag are fixed, and the others are still keeping the automatic behavior?

**Comment by Keenuts** [comment]
Oh got it

**Comment by Keenuts** [comment]
thanks for the finding! pre-reserved the IDs.
If you use the flags, but not the heaps, then the IDs are still reserved. This allow for a much simpler solution (otherwise I'd need to go over resources once to pre-reserve, and then to the normal allocation)

**Review by s-perron — APPROVED** [review]

**Review by cassiebeckley — APPROVED** [review]

**Pull request merged**
