### PR TITLE
Add -fvk-auto-shift-bindings that applies -fvk-*-shift bindings to re…

### LINKED ISSUE #2956: [SPIR-V] Apply binding shifts to resources without register assignments?
_Copying from https://github.com/google/DirectXShaderCompiler/issues/316. All issues should be filed in the Microsoft repository_

<hr/>

From what I have understood (and experimenting with dxc), the -fvk-*-shift arguments provide binding shifts only for those resources that have explicit register assignments.

From https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#implicit-binding-number-assignment it appears that one can provide a descriptor set and otherwise it auto generates a binding:

"If there is no register specification, the corresponding resource will be assigned to the next available binding number, starting from 0, in descriptor set #0 (If -auto-binding-space N command line option is used, then descriptor set #N will be used instead of descriptor set #0)."

In glslang, we use the --auto-map-bindings option which behaves a bit differently in that it auto numbers bindings, but it applies the binding shifts.  So basically what I am looking for is a way to do this:

SamplerState sampler0 : register( s2 );
SamplerState sampler1;
SamplerState sampler2;

I'd like to pass -fvk-s-shift 10 0 and have 

sampler0 <- descriptor set 0, binding 12
sampler1 <- descriptor set 0, binding 10
sampler2 <- descriptor set 0, binding 11

This is what glslang would do.  Is it possible to do this with dxc?

### PR DESCRIPTION
**Pull request by danginsburg**
…sources that do not have explicit register assignments.  Closes #2956

* For resources that don't have an explicit register binding, first categorize their registerType using new method DeclResultIdMapper::getImplicitRegisterType.
* When finding automatic binding indices for implicit register bindings, pass an optional shift to useNextBinding.
* Change getNextBindingChunk() to handle finding the next binding range given a bindingShift

### CODE REVIEW

**Comment by danginsburg** [comment]
Thank you for the thorough review.  It looks like it may be a while until I can address this feedback, so I'd greatly appreciate it if you are able to make these changes @ehsannas

**Comment by ehsannas** [comment]
@danginsburg Happy to help! I think I might be able to do it late next week. Thanks

**Comment by ehsannas** [comment]
Addressed the above issues. Added a test. Updated documentation. Rebased against latest master

**Comment by ehsannas** [comment]
Since I can't/shouldn't review my additions to this PR, I've requested a review from @jaebaek .

@jaebaek PTAL. Thanks!

**Comment by ehsannas** [comment]
buildbot failures are unrelated to this PR. DXC has started treating warnings as error, and tip-of-tree is currently broken because of that.

**Comment by ehsannas** [comment]
I will wait for that issue to be fixed, and then rebase this PR again.

**Comment by danginsburg** [comment]
> Addressed the above issues. Added a test. Updated documentation. Rebased against latest master

Thanks @ehsannas !

**Comment by ehsannas** [comment]
All right. All green. Ready for review.

**Pull request merged**
