### PR TITLE
DXC Release build pipeline - add Linux config, improve display strings

### PR DESCRIPTION
**Pull request by hekota**

### CODE REVIEW

**Review by pow2clk — APPROVED** [review]
Nice to see this go in!

**Comment by MarijnS95** [comment]
@pow2clk I don't mean to be a nuisance, but seeing this PR for Linux what's the status on #3793?

**Comment by pow2clk** [comment]
@Marjin295 Not a nuisance! I completely forgot that it isn't merged 😣. I'm actually working on a change that depends on that, but I just applied it locally. 😕 Sorry about that! I'll include you on the followup to make sure it doesn't disrupt your usages.

**Comment by MarijnS95** [comment]
@pow2clk thanks a ton! Please ping me for anything you have in store, both to test and just because I'm curious/interested :grin:

**Pull request merged**
