### PR TITLE
use llvm::make_unique

### PR DESCRIPTION
**Pull request by ehsannas**
Use llvm::make_unique instead of std::make_unique. Same functionality, fixes some
compiler errors on Linux, and makes the code more consistent with the
rest of the code base.

### CODE REVIEW

**Comment by pow2clk** [comment]
This is an issue I ran into in my implementation as well. I solved it this way for a while, but ended up building with C++14 enabled, which works as well. One question I've meant to ask is what is the maximum C++ version we're willing to use? I have no preference really. Either solution works.

**Comment by antiagainst** [comment]
I think we are supporting both VS2015 & VS2017. I'm not quite clear about VS2015's C++14 support. It is safer if we can use C++11 features if possible.

**Comment by pow2clk** [comment]
FWIW, wikipedia suggests that VS2015 was the first to support C++2014( https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#32-bit_and_64-bit_versions) But this is the only C++14 feature that the codebase seems to use and doing it this way would allow use on other compilers with greater ease. So I'm all in favor of it.

**Comment by antiagainst** [comment]
@pow2clk: Oh, good to know! I don't have strong opinions on it then. But since it will be effective for the whole codebase, Microsoft may want to weigh in.

**Pull request merged**
