### PR TITLE
Restrict parameters to Interlocked* Intrinsics

### LINKED ISSUE #2077: Crash on calling Interlocked*** with non-int/uint type
Repro (`-T vs_6_2 -enable-16bit-types`):
```
groupshared uint gs_uint;
groupshared int gs_int;
groupshared bool gs_bool;
groupshared float gs_float;
groupshared int16_t gs_int16;
groupshared int64_t gs_int64;

void main()
{
  InterlockedAdd(gs_uint, 1);
  InterlockedAdd(gs_int, 1);
  // All the below crash
  InterlockedAdd(gs_bool, 1);
  InterlockedAdd(gs_float, 1);
  InterlockedAdd(gs_int16, 1);
  InterlockedAdd(gs_int64, 1);
}
```

This is likely due to the weird special cases we have for `Interlocked***`'s first parameter not being marked `inout` but being special-cased to become a reference type.

### LINKED ISSUE #2483: dxc silently crashes for atomic ops involving unsupported types
The below one fails to compile on FXC with an error message `"cs_5_1 only supports interlocked operations on scalar int or uint data"`, but silently crashes when compiled using DXC.

```
RWBuffer<float> test;
[numthreads(8,8,1)]
void main() {
  InterlockedAdd(test[0],1.f);
}
```

### PR DESCRIPTION
**Pull request by pow2clk**
Because the defined types of Interlocked* Parameters do not restrict
type casting, they can result in late errors that cause crashes due to
reference params with casts that aren't actually respected by dxil
generation.

By constraining the parameters as they should be, instead of crashes, we
get errors.

Fixes #2077
Fixes #2483

### CODE REVIEW

**Comment by vcsharma** [comment]
```
RWBuffer<float> test;
void main() {
  InterlockedAdd(test[0], 1.f);
}
```
 error: no matching function for call to 'InterlockedAdd'
  InterlockedAdd(test[0], 1.f);
  ^~~~~~~~~~~~~~
note: candidate function not viable: no known conversion from **'float' to 'short &' for 1st argument**

I found the above highlighted part of the warning a bit confusion. Where is "short &" coming from?

**Comment by pow2clk** [comment]
I couldn't tell you. That's not the result I get from applying this change and compiling the shader you included. Here's what I get:

```hlsl
RWBuffer<float> test;
void main() {
  InterlockedAdd(test[0],1.f);
}
```

`dxc.exe -T vs_6_0 2483.hlsl` yields:

```
2483.hlsl:3:3: error: no matching function for call to 'InterlockedAdd'
  InterlockedAdd(test[0],1.f);
  ^~~~~~~~~~~~~~
note: candidate function not viable: no known conversion from 'float' to 'int &' for 1st argument
```

**Comment by vcsharma** [comment]
never mind. I rebuilt your changes locally and I can see the same warning as you do.

**Comment by pow2clk** [comment]
Vishal and I resolved his issue. 

I'm looking at the spir-v test failures. I should start testing them regularly 🤔

**Comment by ehsannas** [comment]
@pow2clk Thanks for fixing this.We had tried to stop bad parameter types for Interlocked* methods by checking the param type in the SPIR-V backend. Glad it's now fixed in the frontend.

**Comment by pow2clk** [comment]
Spir-v test should be resolved. @ehsannas let me know if it looks alright.

As a result of this error from SpirvEmitter.cpp may no longer be needed:
```c++
  if (!baseType->isIntegerType()) {
    emitError("can only perform atomic operations on scalar integer values",
              dest->getLocStart());
    return nullptr;
  }
```
but it doesn't hurt much to have a backstop.

**Comment by ehsannas** [comment]
Yup. Looks good to me. We can keep the check in the backend too. Thanks for the fix.

**Pull request merged**
