### PR TITLE
Fix declaration of IDxcRewriter2 cross-platform uuidof

### PR DESCRIPTION
**Pull request by antiagainst**

### CODE REVIEW

**Comment by antiagainst** [comment]
The tests are already failing on master branch because #1529: https://ci.appveyor.com/project/antiagainst/directxshadercompiler/build/1.0.664/tests

FYI: @hekota

**Comment by antiagainst** [comment]
Buidbot failure is unrelated to this PR, which should fix compilation failure on non-Windows platofrms. I'll merge this one.

**Comment by hekota** [comment]
The tests failures have been caused by unfortunate create/merge timing of PR #1529 and #1535. 
The first PR (#1529) was created before the second one (#1535) but merged after it. #1535 introduced a new flag HLSLOptions.EnableBackCompatMode, which #1529 did not propagate to the compiler because it did not exist then.

**Comment by ehsannas** [comment]
Thanks for the fix.

**Pull request merged**
