### PR TITLE
[linux-port] DxilContainer/ModuleTest on Unix

### PR DESCRIPTION
**Pull request by pow2clk**
Mostly just excluding portions that require reflection allows this
test to run with the usual corralling of header files behine a WIN32
ifdef and adding the gtest inheritence for non-win.
Change an include file capitalization so it can be found on case
sensitive filesystems.

### CODE REVIEW

**Comment by pow2clk** [comment]
Failures on clang compilers. Strange. I tested this on my own clang build just before uploading.

**Comment by pow2clk** [comment]
This is actually two bugs. One is an ambiguity with wcsstr on mac, which just looks like Apple tripping on its shoelaces and falling on its face, but I can install a guardrail to help the poor thing out.

The next is another symptom of ubuntu 14.04 being a product of its time when c++11 was scary and no one dared say its name above a furtive whisper let alone implement it completely. This came up before when the GCC version just wasn't going to cut it and we installed packages to deal with it. This time instead of GCC, I think it's libstdc++. I'm going to try solving it the same way.

**Comment by pow2clk** [comment]
In case this was missed, the latest run was successful, Ubuntu has the package it needs and Apple has the kevlar socks forced on its feet to keep it from shooting itself there.

**Comment by ehsannas** [comment]
Latest HLSL test output on non-windows platforms:

```
[==========] Running 312 tests from 10 test cases.
[----------] Global test environment set-up.
[----------] 3 tests from AllocatorTest
[----------] 3 tests from AllocatorTest (1 ms total)
[----------] 9 tests from DxilContainerTest
[----------] 9 tests from DxilContainerTest (18 ms total)
[----------] 10 tests from DxilModuleTest
[----------] 10 tests from DxilModuleTest (19 ms total)
[----------] 31 tests from DXIntellisenseTest
[----------] 31 tests from DXIntellisenseTest (18 ms total)
[----------] 3 tests from FunctionTest
[----------] 3 tests from FunctionTest (796 ms total)
[----------] 10 tests from ObjectTest
[----------] 10 tests from ObjectTest (164 ms total)
[----------] 4 tests from OptimizerTest
[----------] 4 tests from OptimizerTest (838 ms total)
[----------] 14 tests from SystemValueTest
[----------] 14 tests from SystemValueTest (1507 ms total)
[----------] 186 tests from ValidationTest
[----------] 186 tests from ValidationTest (726 ms total)
[----------] 42 tests from VerifierTest
[----------] 42 tests from VerifierTest (374 ms total)
[----------] Global test environment tear-down
[==========] 312 tests from 10 test cases ran. (4461 ms total)
[  PASSED  ] 312 tests.
```
Great progress.

**Pull request merged**
