### PR TITLE
build: update config.guess and config-ix.cmake

### PR DESCRIPTION
**Pull request by FantasqueX**
- Update config.guess to latest version to make it able to guess recent architectures
- Update config-ix.cmake to update config-ix.cmake to support more architectures
- Tested on riscv64

The initial motivation is to make DirectXShaderCompiler be built on riscv64. However, this change may benefit to other architectures.

### CODE REVIEW

**Comment by FantasqueX** [comment]
@microsoft-github-policy-service agree

**Comment by llvm-beanz** [comment]
We cannot accept updating config.guess. The newest version is under a license that is incompatible with DXC's license.

**Comment by llvm-beanz** [comment]
As a secondary note, the Microsoft CLA that you have to agree to in order to make contributions to this repository requires that you own the copyright of any works that you contribute. Since config.guess is a FSF project, copyrighted by the FSF, this contribution does not mee the requirements of the CLA.

If you need RISCV support you need to implement it manually in the version of config.guess already present in the repository.

**Comment by FantasqueX** [comment]
Really sorry for CLA problem. I will take it carefully next time.

**Pull request closed without merging**
