### PR TITLE
Enable to detect DIA SDK in VS2019

### PR DESCRIPTION
**Pull request by gongminmin**

### CODE REVIEW

**Comment by gongminmin** [comment]
Wait a min. It still breaks when building with Ninja+VS2019. Fixing.

**Comment by MrTrillian** [comment]
Nice!

**Comment by MrTrillian** [comment]
Sorry for not merging earlier @gongminmin ! I hadn't realized you didn't have merge rights

**Comment by gongminmin** [comment]
It's alright. Thanks for merging this!

**Pull request merged**
