### PR TITLE
Hide Unix symbols by default

### LINKED ISSUE #2203: Linux build should not export symbols across shared object boundary by default
Linux build needs options: `-fvisibility=hidden` and `-fvisibility-inlines-hidden` to prevent things such as class methods from being exported across module boundaries by default.  This caused unexpected things to happen with PR #2196 on linux only.  The potential for this to happen elsewhere is very worrying.  PR #1760 adds the default visibility attributes to the explicitly exported APIs (and should be merged), but doesn't appear to add the build flag required to change the default visibility to hidden.

While I see usage of `#pragma GCC visibility push(hidden)` in at least `dxcmem.cpp`, this does not apply to class methods (see: https://gcc.gnu.org/onlinedocs/gcc/Visibility-Pragmas.html), and it doesn't seem sufficient to prevent accidentally exporting symbols not meant for export from elsewhere.  Nothing but the explicitly marked public functions should be exported across the shared library boundary.  Changing the default globally in build settings appears to be the more sensible way to handle this issue.

@ehsannas, what are your thoughts on this?

### PR DESCRIPTION
**Pull request by pow2clk**
Using the -fvisibility=hidden by default only exposes symbols that have
the __attribute__((visibility("default"))) attribute applied to them.
There are only a couple of functions that are meant to be exposed from
libdxcompiler. To expose the proper functions, the macros used to create
the UUIDs for class types are redefined with the attribute and
DXC_API_IMPORT is defined with the attribute above for non-windows
platforms.

Since we're hiding everything now, the portions that were explicitly
hidden to make MacOS work are removed.

This exposed a number of missing dependencies of libraries and unit
tests. Namely clang-hlsl-tests, clang-spirv-tests, and libclangCodeGen.

Resolves #2203

### CODE REVIEW

**Comment by pow2clk** [comment]
Well my memory was wrong, something changed in the meantime, or I'm just amazing. With relatively minimal effort I believe this resolves #2203 and it passes testing on my local Linux and MacOS systems. So maybe I was declaring the sky falling unnecessarily. Nice to have that squared away regardless.

There were a few complications because some lunatic went and ported a bunch of Dxil tests to Linux :stuck_out_tongue_winking_eye:

**Comment by ehsannas** [comment]
Awesome work @pow2clk ! Thank you 👍 

Let's also remove [the workaround](https://github.com/microsoft/DirectXShaderCompiler/pull/2196/commits/398779c10abf0447b9e5a6e28d06627088f26033) that motivated this change.

**Comment by pow2clk** [comment]
Done!

**Comment by ehsannas** [comment]
I'll wait for @tex3d 's approval before merging.

**Pull request merged**
