### PR TITLE
[Build] Update to clang-18 for linux clang pipeline

### PR DESCRIPTION
**Pull request by python3kgae**
This is to work around LeakSanitizer issue 'LeakSanitizer has encountered a fatal error.'

For #6769

### CODE REVIEW

**Review by pow2clk — APPROVED** [review]
Looks good. Let's try to remember to revisit this when the ubuntu images get updated and we can probably get this through apt at least.

**Comment by python3kgae** [comment]
> Looks good. Let's try to remember to revisit this when the ubuntu images get updated and we can probably get this through apt at least.

The best I can get from apt is 15 now.
Not sure how long it will take to get 18.

**Review by damyanp — APPROVED** [review]
Is this a "workaround" or a "fix"?  ie does clang-18 actually fix something, or has this just rearranged things so that the bug no longer shows up?

**Comment by python3kgae** [comment]
> Is this a "workaround" or a "fix"? ie does clang-18 actually fix something, or has this just rearranged things so that the bug no longer shows up?

./llvm.sh 18 will install clang18 and libclang-rt.
The libclang-rt included LeakSanitizer.
It is hard to say its clang18 fixed the issue or updated LeakSanitizer fixed the issue, or it is just rearranged things, so the bug no longer shows up.

What we know is that the failed tests didn't leak memory, and update to clang18 (which will update LeakSanitizer the same time) make the test not fail anymore. Without clang18 update, it is reported as pass in gtest but LeakSanitizer crash make it fail.

**Pull request merged**
