### PR TITLE
Use CreateFileW instead of CreateFile2

### PR DESCRIPTION
**Pull request by antiagainst**
CreateFile2() is only available from Windows 8. Changed to use CreateFileW(),
which is more widely supported.

Fixes https://github.com/Microsoft/DirectXShaderCompiler/issues/1265

### CODE REVIEW

**Comment by antiagainst** [comment]
This fix follows the suggestion in #1265. However, I don't have a  machine running Windows 7. So @tim4864 or @chaoticbob, could you test it out? Thanks!

**Comment by tim4864** [comment]
Thank you @antiagainst.
However, I pulled the latest version today and it seems that the fix is still not on the master branch.
So I couldn't test it yet.

**Comment by pow2clk** [comment]
@tim4864  the fix won't be in the master branch until this pull request is merged. However, the idea is to test it before it will be merged. The simplest way I know to do that is to sync @antiagainst's topic branch. To do that from the command line:

git remote add antiagainst https://github.com/antiagainst/DirectXShaderCompiler.git
git fetch antiagainst
git checkout -b create-file-w -t antiagainst/create-file-w

The last command creates a new local branch that will track @antiagainst's topic branch.  From there, you should be able to build as normal with the change and run it.

Forgive me if I'm telling you things you know. From your comment it seemed this information might be useful.

I took interest because I'm touching on these functions in another change and I'd like to know if this is going to land or not.

**Comment by antiagainst** [comment]
Hey, this pull request has been here for a while. Any chance it gets reviewed? :)

**Comment by antiagainst** [comment]
Thanks for the review, @hekota! :)

**Comment by tim4864** [comment]
@pow2clk Yeah. Your information is really useful! Thanks. :D
@antiagainst Sorry for the late reply. It also works well for me. Thanks for the fix. :)

**Comment by hekota** [comment]
@tim4864, have you been able to verify this on Windows 7?

**Pull request merged**
