### PR TITLE
[lit] Simplify regex for dxil version check.

### PR DESCRIPTION
**Pull request by python3kgae**
Check dxc version and dxil version separately.

### CODE REVIEW

**Review by tex3d — COMMENTED** [review]
Did you run tests with a 1.7 or 1.6 DXIL.dll present to verify that all tests pass?  Here's a couple of SM 6.8 tests that I hit failures on recently when doing so, which do not appear to have `REQUIRES: dxil-1-8` in a comment to prevent running on an older validator.

```
D:\git\dxc\main\tools\clang\test\CodeGenDXIL\hlsl\objects\NodeObjects\array-in-workgraphrecord-1.hlsl
D:\git\dxc\main\tools\clang\test\CodeGenDXIL\hlsl\objects\NodeObjects\array-in-workgraphrecord-2.hlsl
```

**Review by pow2clk — APPROVED** [review]
Thanks for the test change inclusion!

**Comment by python3kgae** [comment]
> Did you run tests with a 1.7 or 1.6 DXIL.dll present to verify that all tests pass? Here's a couple of SM 6.8 tests that I hit failures on recently when doing so, which do not appear to have `REQUIRES: dxil-1-8` in a comment to prevent running on an older validator.
> 
> ```
> D:\git\dxc\main\tools\clang\test\CodeGenDXIL\hlsl\objects\NodeObjects\array-in-workgraphrecord-1.hlsl
> D:\git\dxc\main\tools\clang\test\CodeGenDXIL\hlsl\objects\NodeObjects\array-in-workgraphrecord-2.hlsl
> ```

Yes. It passes with this fix.

**Comment by tex3d** [comment]
> > Did you run tests with a 1.7 or 1.6 DXIL.dll present to verify that all tests pass? Here's a couple of SM 6.8 tests that I hit failures on recently when doing so, which do not appear to have `REQUIRES: dxil-1-8` in a comment to prevent running on an older validator.
> > ```
> > D:\git\dxc\main\tools\clang\test\CodeGenDXIL\hlsl\objects\NodeObjects\array-in-workgraphrecord-1.hlsl
> > D:\git\dxc\main\tools\clang\test\CodeGenDXIL\hlsl\objects\NodeObjects\array-in-workgraphrecord-2.hlsl
> > ```
> 
> Yes. It passes with this fix.

I don't see how these can tests pass when they require SM 6.8 and do not state the requirement.  Shouldn't these tests be gated on the dxil-1-8 requirement?

What method did you use to test against older DXIL.dll?  The hcttest.cmd option has been broken since moving to lit.  You have to manually add the DXIL.dll to both `bin` and `test` directories under your configuration to make sure it runs tests using it.

Also, these tests were introduced in a change which has a cherry-pick PR to release branch: #6326.  We do want to get that change into release, but not if these tests break integration.

**Comment by python3kgae** [comment]
> > > Did you run tests with a 1.7 or 1.6 DXIL.dll present to verify that all tests pass? Here's a couple of SM 6.8 tests that I hit failures on recently when doing so, which do not appear to have `REQUIRES: dxil-1-8` in a comment to prevent running on an older validator.
> > > ```
> > > D:\git\dxc\main\tools\clang\test\CodeGenDXIL\hlsl\objects\NodeObjects\array-in-workgraphrecord-1.hlsl
> > > D:\git\dxc\main\tools\clang\test\CodeGenDXIL\hlsl\objects\NodeObjects\array-in-workgraphrecord-2.hlsl
> > > ```
> > 
> > 
> > Yes. It passes with this fix.
> 
> I don't see how these can tests pass when they require SM 6.8 and do not state the requirement. Shouldn't these tests be gated on the dxil-1-8 requirement?
> 
> What method did you use to test against older DXIL.dll? The hcttest.cmd option has been broken since moving to lit. You have to manually add the DXIL.dll to both `bin` and `test` directories under your configuration to make sure it runs tests using it.
> 
> Also, these tests were introduced in a change which has a cherry-pick PR to release branch: #6326. We do want to get that change into release, but not if these tests break integration.

This part is already in with https://github.com/microsoft/DirectXShaderCompiler/commit/76f00d05f4816018dedd7375780785deee12e3f9

This PR is fix the issue about dxil version parsing.

**Review by tex3d — APPROVED** [review]
Ok, looks good.

**Pull request merged**
