### PR TITLE
Correct the validation of vk::image_format. Fixes #5189

### LINKED ISSUE #5189: [SPIRV] vk::image_format can't be used in arrays of RWTexture or [RW]Buffer
The following:

```
[[vk::binding(0), vk::image_format("r32ui")]] RWTexture2D<uint> g_hzbUavTex[2];
[[vk::binding(1), vk::image_format("r32ui")]] Buffer g_buff[2];

float4 PSMain() : SV_TARGET
{
	return 0;
}
```

fails to compile with the message:

```
D:\local\Temp\dba87ada-0f40-41c0-8ab4-009ee209902d.hlsl:1:19: error: 'image_format' attribute only applies to RWTextures, Buffers and RWBuffers
[[vk::binding(0), vk::image_format("r32ui")]] RWTexture2D<uint> g_hzbUavTex[2];
                  ^
D:\local\Temp\dba87ada-0f40-41c0-8ab4-009ee209902d.hlsl:2:19: error: 'image_format' attribute only applies to RWTextures, Buffers and RWBuffers
[[vk::binding(1), vk::image_format("r32ui")]] Buffer g_buff[2];
```

It seems the validation for the image_format attribute is wrong it should include arrays as well.

### PR DESCRIPTION
**Pull request by godlikepanos**
Please disregard that the fork is from KhronosGroup. This was an accident.

### CODE REVIEW

**Comment by godlikepanos** [comment]
@microsoft-github-policy-service agree

**Comment by s-perron** [comment]
Could you please add a test?

**Comment by s-perron** [comment]
You can add the HLSL file to this directory the the appropriate lit checks. It should check for the variable and make sure it is the correct type.

Then add the file to the list of file tests: 

https://github.com/microsoft/DirectXShaderCompiler/blob/2dd8344cc395a21aecdebf410af7960ddd610125/tools/clang/unittests/SPIRV/CodeGenSpirvTest.cpp#L71

**Comment by godlikepanos** [comment]
Thank you. While writing the test I realized that there might be an additional issue with vk::image_format. Will try to verify and fix that as well.

**Comment by godlikepanos** [comment]
@s-perron @Keenuts I've added a unit test and also fixed an additional bug. The bug is that then there is OpTypeArray between OpVariable and OpTypeImage the format will get lost. 

Also some notes:
- It seems that the SPIR-V tests don't run when typing `ctest`. Had to run them manually using `clang-spirv-tests`
- I couldn't find any documentation on how to run the tests to be honest. If there is something written I totally missed it
- This is my first time touching LLVM/clang code. Please give it an extra look to make sure everything is correct

Thank you!

**Comment by Keenuts** [comment]
Thanks, looking into this!

> * It seems that the SPIR-V tests don't run when typing `ctest`. Had to run them manually using `clang-spirv-tests`

@llvm-beanz made a lot of work so it's now part of the LIT test framework.
The actual steps are documented in `docs/BuildingAndTestingDXC.rst`
(but yes, the main README doesn't mention it)

Those are the commands I use:
```
cmake -Bbuild -GNinja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_INSTALL_PREFIX=artifacts \
    -DDXC_USE_LIT=ON \
    -DENABLE_SPIRV_CODEGEN=ON \
    -DSPIRV_BUILD_TESTS=ON \
    -C cmake/caches/PredefinedParams.cmake
ninja -C build check-all
```

**Review by Keenuts — APPROVED** [review]
LGTM, thanks :)

**Pull request merged**
