### PR TITLE
[SPIRV] Fix missing implicit decls

### PR DESCRIPTION
**Pull request by jiaolu**
Trying to add astcontext decls to the astDecls tables if decl is not
inserted at the beginning.

### CODE REVIEW

**Comment by Jasper-Bekkers** [comment]
This fixes the issue for us.

**Comment by Jasper-Bekkers** [comment]
Might be good to add a unit test for this, since the repro was about the simplest possible RayQuery example. It would be a shame if something breaks with it again

**Comment by jiaolu** [comment]
Move the review discussion:
from @alelenv
Is the issue enums like COMMITTED_TRIANGLE_HIT not being present in astDecls before use?
I think adding to getDeclEvalInfo is not correct and you should add them in doImplicitDecl similar to other enums for ray tracing

If i add constant In doImplicitDecl, or remove "spvContext.isRay()", then regression tests would fail, there are 17 tests failed:
e.g. WholeFileTest.PassThruPixelShader, because the doImplicitDecl would add raytracing/rayquery constants regardlessly for every shader.

**Comment by Jasper-Bekkers** [comment]
Looks like the test fails because the OpConstants and OpType*'s don't get DCE'd completely. IIRC spirv-opt does have a pass to remove such things, so that may be an option.

**Comment by jiaolu** [comment]
> Looks like the test fails because the OpConstants and OpType*'s don't get DCE'd completely. IIRC spirv-opt does have a pass to remove such things, so that may be an option.

clang-spirv-tests use specific options: "-fcgl -Vd", so the spirv generated is some how without optimization with added OpConstant.

**Comment by pow2clk** [comment]
If you put "Fixes #3047" in the commit comment, the bug will be close automatically when this is submitted. Putting it in the title just makes it confusing next to the PR number that gets added automatically.

**Comment by ehsannas** [comment]
I'll take a closer look later this week.

**Comment by ehsannas** [comment]
Fixes #3047

**Comment by ehsannas** [comment]
@alelenv @jiaolu I have changed the backend code to "lazily" create SPIR-V instructions for implicit VarDecls. This is a more general solution I believe, and it is not raytracing-specific. I can foresee other use cases where the front-end might create implicit decls.

**Comment by jiaolu** [comment]
> @alelenv @jiaolu I have changed the backend code to "lazily" create SPIR-V instructions for implicit VarDecls. This is a more general solution I believe, and it is not raytracing-specific. I can foresee other use cases where the front-end might create implicit decls.

thanks a lot.

**Pull request merged**
