### PR TITLE
Adding test fixes and more support for SM6.5 WaveMultiPrefix functions

### PR DESCRIPTION
**Pull request by paigeale**
1)	Ensure wave lane-id’s are sorted when accumulating result
2)	Fix made for HLSL in ShaderOpArithTable.xml to ensure the input aligns with what is being tested
3)	Added support for the “UBit” version for all of these tests.

### CODE REVIEW

**Comment by hekota** [comment]
@paigeale - the ShaderOpArithTable.xml is not edited directly but generated by `utils\hct\hctdb_test.py gen-xml`. Can you please modify the hctdb_test.py file to generate the code change you want in ShaderOpArithTable.xml? You might have to add a new item in `g_shader_texts` to accomate the `> 10` change. Let me know if you have any questions.

**Comment by paigeale** [comment]
@hekota, 

Thanks I will upload the change for the hctdb_test.py .

Looks like there are two options (I will gladly implement either )
1) Modify hctdb_test.py and add a new g_shader_texts entry with **%s(data.value > 10, mask)**
2) Modify hctdb_test.py and change the input list going into WaveMultiPrefixCountBits to have 0 values, and modify tools\clang\unittests\HLSL\ExecutionTest.cpp tests from this
 **return [] (T lhs, T rhs) -> T { return lhs + (rhs > 10 ? 1 : 0); };**
 to this
 **return [] (T lhs, T rhs) -> T { return lhs + (rhs ? 1 : 0); };**

Please let me know what you prefer.

**Comment by hekota** [comment]
I think option #2 would be better, less code duplication.

**Comment by hekota** [comment]
> @hekota Is my latest change acceptable?

Sorry about the delay. I started the review but then got caught up in something else.

**Comment by paigeale** [comment]
Thanks for taking the time to review @hekota. I added one more commit with the whitespaces fixed up. Let me know if there is anything else needed on my side before this change can go in.

**Comment by hekota** [comment]
Thanks @paigeale !

**Pull request merged**
