### PR TITLE
Disable linux requirement in Travis due to unresolved infra issue

### PR DESCRIPTION
**Pull request by tex3d**

### CODE REVIEW

**Review by pow2clk — APPROVED** [review]
Looks good! The advantage is that this will still run the tests. Let's not forget to enable again when they start passing again :)

**Comment by pow2clk** [comment]
Added @ehsannas in case he has more information

**Comment by tex3d** [comment]
> Looks good! The advantage is that this will still run the tests. Let's not forget to enable again when they start passing again :)

Yes :)

**Comment by tex3d** [comment]
Unfortunately, this doesn't prevent Travis from still blocking PRs until it times out many hours later.  So we still have to override checks to merge earlier.  That is unless Ehsan knows how to turn off these checks for PR and CI builds.  Removing from readme didn't work, and I can't find any setting or other reference to do this.

**Pull request merged**
