### PR TITLE
[lit][SPIRV] convert runCodeTest to lit and remove dependence on effcee

### PR DESCRIPTION
**Pull request by python3kgae**
Convert runCodeTest to lit FileCheck test and remove all the code related to runCodeTest.

Remove effcee and re2 from git submodule since nothing is dependent on them after the change.

### CODE REVIEW

**Comment by s-perron** [comment]
FYI: #6085 wants to add a new codegentest. This is possibly one that cannot be done by calling dxc from the command line.

**Comment by python3kgae** [comment]
> FYI: #6085 wants to add a new codegentest. This is possibly one that cannot be done by calling dxc from the command line.

So I should not remove FileTestFixture and FileTestUtils?

**Review by sudonatalie — APPROVED** [review]
nit: Can you move these tests from `CodeGenSPIRV/legacy-runCodeTest` to the base `CodeGenSPIRV` dir? We don't need to maintain a distinction between old runCodeTest/FileTest.

Otherwise looks good, thanks for making these changes!

**Comment by python3kgae** [comment]
> nit: Can you move these tests from `CodeGenSPIRV/legacy-runCodeTest` to the base `CodeGenSPIRV` dir? We don't need to maintain a distinction between old runCodeTest/FileTest.
> 
> Otherwise looks good, thanks for making these changes!

Updated.
Thanks for the review.

**Review by Keenuts — APPROVED** [review]

**Comment by SteveUrquhart** [comment]
> FYI: #6085 wants to add a new codegentest. This is possibly one that cannot be done by calling dxc from the command line.

The test in #6085 does require dxcompiler.dll, as does InlinedCodeTest and several of the tests affected here.  How is it planned to continue this testing?

**Comment by s-perron** [comment]
@SteveUrquhart If something that you need was removed by this PR, you can bring it back in, but it will need to be changed to not rely on effcee. I can help get the infrastructutre that you need back, if you can tell me exactly what you need. We could easily add classes that would take the HLSL as a string, compile it, and then return the spir-v assembly as a string. We no longer have effcee and re2 to do string matching. What would you need?

The tests that were removed by this PR were either replaced with new tests or no longer needed. For example the InlinedCode tests only tested infrastructure, and did not test any DXC features.

**Comment by SteveUrquhart** [comment]
We need a test.exe that links against dxcompiler.dll to test dll-only bugs such as https://github.com/microsoft/DirectXShaderCompiler/pull/6085.  Many toolchains use the dll interface instead of dxc.exe. The input string is simply passed through, dll users don’t need string matching.

**Pull request merged**
