### PR TITLE
Removed OS condition to install DXCompiler

### PR DESCRIPTION
**Pull request by bmarques1995**
added the archive(.lib) file to dxcompiler install

### CODE REVIEW

**Review by llvm-beanz — COMMENTED** [review]
I think the more correct fix to this bug is to change the `add_clang_library` macro defined in `tools/clang/CMakeLists.txt` to treat `dxcompiler` the same way it treats `libclang`.

**Comment by llvm-beanz** [comment]
I believe this is intended to fix #5682.

**Comment by bmarques1995** [comment]
> I believe this is intended to fix #5682.

you're correct, i will look this

**Comment by bmarques1995** [comment]
> I believe this is intended to fix #5682.

By the way, are you one of the analysers of this issue? I believe u've looked that I made it

**Comment by bmarques1995** [comment]
> I believe this is intended to fix #5682.

I've modified my PR, now I removed the OS condition to install target, this is unnecessary, cmake automaticly manages the binaries(runtime [executable and DLLs], library [static libs on Windows, or all libs on another distros] and archive[symbols{...dll.lib}]) of all OS, depending the target

**Comment by bmarques1995** [comment]
> @bmarques1995 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Review by llvm-beanz — CHANGES_REQUESTED** [review]
This is much more complicated than it needs to be. You should be able to add dxcompiler here:

https://github.com/microsoft/DirectXShaderCompiler/blob/main/tools/clang/CMakeLists.txt#L377


The stuff you're doing with the `find_*` is also not correct. I don't think we should make a DXC-specific CMake exports list because ultimately DXC is just a fork of LLVM. I think it would be better to connect these through the existing export mechanism for LLVM targets.

**Comment by bmarques1995** [comment]
> This is much more complicated than it needs to be. You should be able to add dxcompiler here:
> 
> https://github.com/microsoft/DirectXShaderCompiler/blob/main/tools/clang/CMakeLists.txt#L377
> 
> The stuff you're doing with the `find_*` is also not correct. I don't think we should make a DXC-specific CMake exports list because ultimately DXC is just a fork of LLVM. I think it would be better to connect these through the existing export mechanism for LLVM targets.

this is the only problem or don't you agree also with the new runtime syntax? if is this the case i discard the change of find_package export, but the first one for me is critical, to move the install syntax

**Pull request closed without merging**
