### PR TITLE
Enabled D3DCOMPILE_ENABLE_BACKWARDS_COMPATIBILITY support (closes #2571)

### LINKED ISSUE #2571: Enable D3DCOMPILE_ENABLE_BACKWARDS_COMPATIBILITY
Older semantics support are already implemented and we need to just enabled the flag.

Otherwise, what's the point of supporting /Gec command line key, but not supporting `D3DCOMPILE_ENABLE_BACKWARDS_COMPATIBILITY`?

### PR DESCRIPTION
**Pull request by Xottab-DUTY**

### CODE REVIEW

**Comment by Xottab-DUTY** [comment]
After merging this you should update [D3DCompiler DXC Bridge](https://github.com/microsoft/DirectXShaderCompiler/wiki/D3DCompiler-DXC-Bridge) wiki page.

**Comment by Xottab-DUTY** [comment]
Merge when
image

**Comment by pow2clk** [comment]
Sorry for the delay. This got lost in the shuffle.

**Comment by Xottab-DUTY** [comment]
Thank you 😃

**Pull request merged**
