### PR TITLE
[SPIRV] Support 16-bit Type Cast Intrinsics

### PR DESCRIPTION
**Pull request by gmitrano-unity**
This change adds support for 16-bit type cast intrinsics by routing them into the same logic used by the 32-bit type casts. With this change in place, asfloat16, asint16, and asuint16 are now translated into OpBitcast in SPIR-V.

This change also includes new partial disassembly tests for each function similar to the ones used for 32-bit casts.

### CODE REVIEW

**Review by cassiebeckley — CHANGES_REQUESTED** [review]
Could you update the documentation comments in `processIntrinsicAsType` on I believe line 10112 of SpirvEmitter.cpp? Other than that, this looks great!

**Review by cassiebeckley — APPROVED** [review]
LGTM, thanks for the contribution!

**Comment by gmitrano-unity** [comment]
> LGTM, thanks for the contribution!

You're very welcome! Thanks for the quick review! 🙂

**Comment by gmitrano-unity** [comment]
Hmmm, did the license/cla job get stuck or did I miss a step? That check has been running for 16+ hrs.

**Comment by vettoreldaniele** [comment]
Looks like there are two CLA jobs, not sure if this is a recent change. Can you try force pushing to retry the checks?

**Comment by vettoreldaniele** [comment]
@pow2clk Do you happen to know what's up with the double CLA check?

**Comment by vettoreldaniele** [comment]
@tex3d Adding more folks from Microsoft to see if they can help with the CLA issue.

**Comment by pow2clk** [comment]
We've been having some issues with the CLA check recently. I'm not sure what the cause is. I'm looking into it.

**Comment by pow2clk** [comment]
Looks like I cleared the logjam! Fire when ready!

**Pull request merged**
