### PR TITLE
Fix assert when a function been called more than once by entry.

### PR DESCRIPTION
**Pull request by python3kgae**
For better support for noinline.

If a function is processed, just skip in DxilViewIdStateBuilder::ComputeReachableFunctionsRec.

### CODE REVIEW

**Review by pow2clk — APPROVED** [review]
Looks good. Can this not be triggered from HLSL? It's fine if not, we want to have more unit testy unit tests. I'm just curious

**Comment by python3kgae** [comment]
> Looks good. Can this not be triggered from HLSL? It's fine if not, we want to have more unit testy unit tests. I'm just curious

It sure can. I thought our new style for test is opt only. :)

**Review by llvm-beanz — COMMENTED** [review]
I think the gap in test coverage here is that we're not actually verifying that the changed code behaves correctly, we're verifying it doesn't crash/assert.

We should probably have a printer for the View Id state data, and have that connected to a printing pass that we can run to verify the correct result.

**Comment by python3kgae** [comment]
> I think the gap in test coverage here is that we're not actually verifying that the changed code behaves correctly, we're verifying it doesn't crash/assert.
> 
> We should probably have a printer for the View Id state data, and have that connected to a printing pass that we can run to verify the correct result.

Sure. I can do that in another PR.

**Comment by llvm-beanz** [comment]
> Sure. I can do that in another PR.

If you wan tot do that in a separate PR, that's fine, but this PR should be based on that functionality.

You're changing behavior in this PR that you can't accurately test. So we should make sure the required testing support is available before you change the behavior.

**Comment by python3kgae** [comment]
Redo in https://github.com/microsoft/DirectXShaderCompiler/pull/4992  with dump test.

**Pull request closed without merging**
