### PR TITLE
Create a bot for monitoring bad memory usage (leaks, etc).

### PR DESCRIPTION
**Pull request by ehsannas**

### CODE REVIEW

**Comment by ehsannas** [comment]
Travis results are here: https://travis-ci.org/github/microsoft/DirectXShaderCompiler/builds/718997567

(Travis is not posting its progress/results here. it's not relevant to this PR. It's happening for other PRs too. Will try to figure out what's going on there. It's probably because it has lost authentication privileges to post to github).

**Comment by pow2clk** [comment]
I'm in favor of this. Do you know whether it will add significantly to the build times? It's allowed to fail, but even so, I don't imagine it will return result (once we fix that) until it's complete.

**Comment by ehsannas** [comment]
cool, I can see the memory leaks being reported:
https://travis-ci.org/github/microsoft/DirectXShaderCompiler/jobs/718997574

It's a bit slower than the regular 'release' builds on Linux. but given that most of the travis [jobs](https://travis-ci.org/github/microsoft/DirectXShaderCompiler/builds/718997567) finish in ~30-35 mins, I think this one will take 45-55 mins. and all of these jobs run in parallel. So I think it's not going to be a big hit.

**Comment by pow2clk** [comment]
It looks like all the reported leaks are in spirv. As I understand it, it should produce output for the dxil generating tests too shouldn't it? I'd be surprised if there weren't leaks there too.

**Comment by ehsannas** [comment]
yes, it should.

It's running the following in order:
```
  - ./bin/dxc -T ps_6_0 -Fo passthru-ps.dxil ../tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv  <-- no leaks
  - ./bin/dxc -T ps_6_0 -Fo passthru-ps.spv ../tools/clang/test/CodeGenSPIRV/passthru-ps.hlsl2spv -spirv <-- found leaks
  - ./bin/clang-spirv-tests --spirv-test-root ../tools/clang/test/CodeGenSPIRV/ <-- found leaks
  - ./bin/clang-hlsl-tests --HlslDataDir $PWD/../tools/clang/test/HLSL/ <-- didn't run
```

The last one didn't run it seems. The last line of the log is `The job exceeded the maximum log length, and has been terminated.`

Once the SPIR-V leaks are fixed, the log will be shorter and the HLSL tests should run too.

**Pull request merged**
