### PR TITLE
[SPIR-V] Add support for the extension VK_EXT_mesh_shader

### PR DESCRIPTION
**Pull request by tywuAMD**
Add support for VK-EXT_mesh shader with respect to the following docs:
* https://microsoft.github.io/DirectX-Specs/d3d/MeshShader.html
* https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/EXT/SPV_EXT_mesh_shader.asciidoc

### CODE REVIEW

**Comment by tywuAMD** [comment]
@microsoft-github-policy-service agree [company="AMD"]

**Comment by tywuAMD** [comment]
@microsoft-github-policy-service agree company="AMD"

**Comment by tywuAMD** [comment]
Ready for review

**Comment by Tobski** [comment]
@dnovillo can you help get this reviewed and merged? Thanks!

**Comment by cassiebeckley** [comment]
I'll take a look at this!

**Comment by Tobski** [comment]
> I'll take a look at this!

Thanks!

**Review by cassiebeckley — APPROVED** [review]
LGTM, thanks for adding this feature!

**Comment by SaschaWillems** [comment]
This doesn't seem to work (for me) with both the appveyor build linked here and the latest appveyor build. It always tells me that the `SPV_EXT_mesh_shader` extension is unknown:

```
Compiling V:/Vulkan/Vulkan-Master/data/shaders/hlsl\meshshader\meshshader.mesh 
error: unknown SPIR-V extension 'SPV_EXT_mesh_shader'
```

and shows this list of supported extensions, which is lacking `SPV_EXT_mesh_shader':

```
* KHR
* SPV_KHR_16bit_storage
* SPV_KHR_device_group
* SPV_KHR_fragment_shading_rate
* SPV_KHR_non_semantic_info
* SPV_KHR_multiview
* SPV_KHR_shader_draw_parameters
* SPV_KHR_post_depth_coverage
* SPV_KHR_ray_tracing
* SPV_KHR_shader_clock
* SPV_EXT_demote_to_helper_invocation
* SPV_EXT_descriptor_indexing
* SPV_EXT_fragment_fully_covered
* SPV_EXT_fragment_invocation_density
* SPV_EXT_shader_stencil_export
* SPV_EXT_shader_viewport_index_layer
* SPV_AMD_gpu_shader_half_float
* SPV_AMD_shader_early_and_late_fragment_tests
* SPV_AMD_shader_explicit_vertex_parameter
* SPV_GOOGLE_hlsl_functionality1
* SPV_GOOGLE_user_type
* SPV_NV_ray_tracing
* SPV_NV_mesh_shader
* SPV_KHR_ray_query
* SPV_EXT_shader_image_int64
* SPV_KHR_physical_storage_buffer
* SPV_KHR_vulkan_memory_model
```

I'm using the vulkan1.3 target environment and the ms_6_6 profile.

**Comment by tywuAMD** [comment]
> This doesn't seem to work (for me) with both the appveyor build linked here and the latest appveyor build. It always tells me that the `SPV_EXT_mesh_shader` extension is unknown:
> 
> ```
> Compiling V:/Vulkan/Vulkan-Master/data/shaders/hlsl\meshshader\meshshader.mesh 
> error: unknown SPIR-V extension 'SPV_EXT_mesh_shader'
> ```
> 
> and shows this list of supported extensions, which is lacking `SPV_EXT_mesh_shader`:
> 
> ```
> * KHR
> * SPV_KHR_16bit_storage
> * SPV_KHR_device_group
> * SPV_KHR_fragment_shading_rate
> * SPV_KHR_non_semantic_info
> * SPV_KHR_multiview
> * SPV_KHR_shader_draw_parameters
> * SPV_KHR_post_depth_coverage
> * SPV_KHR_ray_tracing
> * SPV_KHR_shader_clock
> * SPV_EXT_demote_to_helper_invocation
> * SPV_EXT_descriptor_indexing
> * SPV_EXT_fragment_fully_covered
> * SPV_EXT_fragment_invocation_density
> * SPV_EXT_shader_stencil_export
> * SPV_EXT_shader_viewport_index_layer
> * SPV_AMD_gpu_shader_half_float
> * SPV_AMD_shader_early_and_late_fragment_tests
> * SPV_AMD_shader_explicit_vertex_parameter
> * SPV_GOOGLE_hlsl_functionality1
> * SPV_GOOGLE_user_type
> * SPV_NV_ray_tracing
> * SPV_NV_mesh_shader
> * SPV_KHR_ray_query
> * SPV_EXT_shader_image_int64
> * SPV_KHR_physical_storage_buffer
> * SPV_KHR_vulkan_memory_model
> ```
> 
> I'm using the vulkan1.3 target environment and the ms_6_6 profile.

From the error message, to me it seems like the build you were using does not include this whole PR. Could you please try with this one: https://ci.appveyor.com/api/buildjobs/1mqvlh4brtt8x2ch/artifacts/build%2FRelease%2Fdxc-artifacts.zip

**Comment by SaschaWillems** [comment]
I get the same error with the build you linked to. I also tried multiple appveyor builds that were created after this PR has finished, and none of them have `SPV_EXT_mesh_shader`.

**Comment by tywuAMD** [comment]
> I get the same error with the build you linked to. I also tried multiple appveyor builds that were created after this PR has finished, and none of them have `SPV_EXT_mesh_shader`.

Sorry for the late reply. Unfortunately I was not able to reproduce this issue with either the builds you mentioned or the latest build. If it is possible. could you please provide me some steps to reproduce this error so that I could look into it?

**Comment by ashpil** [comment]
It seems that at the moment the spirv backend always requests the `MeshShadingEXT` capability, even if you're not using a mesh shader -- is this expected behavior?
```
Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-01091 ] Object 0: handle = 0x2191370, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xa7bb8db6 | vkCreateShaderModule(): The SPIR-V Capability (MeshShadingEXT) was declared, but none of the requirements were met to use it. The Vulkan spec states: If pCode declares any of the capabilities listed in the SPIR-V Environment appendix, one of the corresponding requirements must be satisfied (https://vulkan.lunarg.com/doc/view/1.3.231.2/linux/1.3-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-01091)
```

**Comment by tywuAMD** [comment]
> It seems that at the moment dxc always requests the `MeshShadingEXT` capability, even if you're not using a mesh shader -- is this expected behavior?
> 
> ```
> Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-01091 ] Object 0: handle = 0x2191370, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xa7bb8db6 | vkCreateShaderModule(): The SPIR-V Capability (MeshShadingEXT) was declared, but none of the requirements were met to use it. The Vulkan spec states: If pCode declares any of the capabilities listed in the SPIR-V Environment appendix, one of the corresponding requirements must be satisfied (https://vulkan.lunarg.com/doc/view/1.3.231.2/linux/1.3-extensions/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-01091)
> ```

No it is not. The `MeshShadingEXT` capability would be enabled only when the current execution shader model is mesh or task, or  the two mesh-specified operations `OpSetMeshOutputsEXT` or `OpEmitMeshTasksEXT` were called.

**Pull request merged**
