### PR TITLE
Add an option to turn on/off debug iterators

### PR DESCRIPTION
**Pull request by gongminmin**
This new option determines whether to define \_ITERATOR_DEBUG_LEVEL=0. By default, that macro is defined.

Related to issue #2864 .

### CODE REVIEW

**Comment by pow2clk** [comment]
I'm afraid I'm getting cold feet. 

I ran some simple tests to determine how much this slows the debug built compiler down, the difference was not significant. Nevertheless, I think I would feel better if there were a cmake define that could enable or disable this even if the default is to not set it to 0.

There is a test in CompilerTest that requires this to be zero. it's not enabled by default, but for its sake, I think we should have a way to set this to zero with the cmake configuration.

**Comment by ehsannas** [comment]
I like the flexibility that a cmake configuration would provide.

@gongminmin I'm curious whether you ran into a situation where this flag caused you trouble? If it's not something many users run into, we should keep the existing behavior (D_ITERATOR_DEBUG_LEVEL=0) as default, and only make it possible to change it via a cmake flag.

**Comment by gongminmin** [comment]
I'm afraid I could run into a corner case. In my project, it depends a lib from SPIRV-Tools, the same lib also get linked to dxc. In this case, I have to add _ITERATOR_DEBUG_LEVEL=0 to the whole project to avoid the conflict. 

At first, my project has STL containers in the interface, which means users also need to set _ITERATOR_DEBUG_LEVEL=0 in their project. As a result, I removed all the STL containers from the interface to avoid the propagation. That's why I'm curious about why dxc has _ITERATOR_DEBUG_LEVEL=0. 

I know there are drawbacks if removing _ITERATOR_DEBUG_LEVEL=0. The binary size of debug build increases ~15%. Should I abandon this PR or add a cmake flag? Thanks.

**Comment by pow2clk** [comment]
@gongminmin I think you have more invested in this than anyone else involved. You can abandon or modify this change as you see fit. I want to make it so you don't have to add the define where it isn't needed. Do you think that adding a cmake option would accomodate your needs?

It is perhaps worth mentioning that the output of an internal compiler crash has been a sore point for some users of the DXC compiler recently. So defaulting to being more informative might not be such a bad way to go.

**Comment by gongminmin** [comment]
I just pushed a new iteration with HLSL_DISABLE_DEBUG_ITERATORS option. By default it's ON, which defines _ITERATOR_DEBUG_LEVEL=0. Do you think it's unnatural to have an option named DISABLE_*? Or I should name it HLSL_ENABLE_* and make the default value OFF?

**Comment by ehsannas** [comment]
HLSL_ENABLE_* with default value of OFF sounds better to me.

**Comment by ehsannas** [comment]
thanks

**Comment by gongminmin** [comment]
Thanks folks!

I'll send out another PR to change it to HLSL_ENABLE_* with default value of OFF.

**Pull request merged**
