### PR TITLE
Remove unsupported /O4 option from help text.

### LINKED ISSUE #661: Remove /O4 support
Not needed for back-compat - should be collapsed into /O3.

### PR DESCRIPTION
**Pull request by MrTrillian**
This was a merely cosmetic issue, /O4 is unrecognized and ignored by the compiler.

Fixes #661

### CODE REVIEW

**Comment by vcsharma** [comment]
@antiagainst @ehsannas just FYI - this change requires minor updates in spirv tests.

**Comment by MrTrillian** [comment]
@tex3d Do you know if this failing test is flaky? It passes on my machine but failed Appveyor:

c:\projects\DirectXShaderCompiler\tools\clang\test\HLSL\..\CodeGenHLSL\quick-test\d3dreflect\lib_hs_export1.hlsl

**Comment by MrTrillian** [comment]
@antiagainst @ehsannas I'm merging this later today unless I hear otherwise!

**Comment by ehsannas** [comment]
@vcsharma Thanks for the heads up. LGTM

**Comment by ehsannas** [comment]
@MrTrillian , Thanks for waiting. Please go ahead and merge

**Pull request merged**
