### PR TITLE
Use std::atomic.

### PR DESCRIPTION
**Pull request by python3kgae**
llvm::sys::Atomic* was removed in upstream llvm.

### CODE REVIEW

**Comment by vcsharma** [comment]
Are these changes ported/cherrypicked from llvm upstream?

**Comment by vcsharma** [comment]
Maybe we should just cherry pick the [patch](https://reviews.llvm.org/D20901) from the upstream?

**Comment by antiagainst** [comment]
This fails Linux & macOS. Please let us fix that before merging. :)

**Comment by ehsannas** [comment]
My commit should fix the issue for Linux/macOS.

There is a full discussion of the issue [here](https://stackoverflow.com/questions/21708606/why-does-an-in-place-member-initialization-use-a-copy-constructor-in-c11).

**Pull request merged**
