### PR TITLE
[spirv] Convert to use 2 as the depth value for OpTypeImage

### PR DESCRIPTION
**Pull request by antiagainst**
2 means no indication as to whether this is a depth or non-depth
image.

Reverted "Hack OpSampledImage for depth-comparison sampling".

This reverts commit 0f165c6483802f84a36ad7275a2c7dc541bddb31.

### CODE REVIEW

**Comment by kennyalive** [comment]
Works fine with NVIDIA drivers 397.31 on GTX 1060. Also the workaround that was reverted produced visual artifacts (shadows were broken in some scenarios). I'm going to check how it works with AMD hardware this week and also for NVIDIA with hotfix drivers released after 397.31. Thank you for your work.

**Comment by oscarbg** [comment]
@kennyalive perhaps is better to test with nvidia vulkan dev drivers as that is will be integrated in future branches like 399 or 400 series.. now latest is 397.54..
AMD are you referring on new branch (18.10) known as 17.4.1 right?
also for completeness will you be able to test on latest Intel Windows Vulkan 1.1 driver (24.20.100.6025 WHQL)?

**Comment by tafuri** [comment]
There are now tests for this issue in the CTS https://github.com/KhronosGroup/VK-GL-CTS/issues/88 also. Which should accelerate conformance.

**Comment by kennyalive** [comment]
@oscarbg Tested today with 397.54. It seems shadows works as expected. Probably won't be able to check intel compatibility in the near future. Not sure about AMD drivers version, I'm going to do some tests on Friday and I'll provide and update.

**Comment by kennyalive** [comment]
The shadows also present on AMD Vega 64. Currently I have public 18.3.4 drivers installed with updated  amdvlk64.dll vulkan driver, we use dev version released on 08.05.2018.

**Comment by antiagainst** [comment]
Cool! Thanks for your diligence, @kennyalive! I'll merge this then.

**Pull request merged**
