### PR TITLE
 [spirv] Added new offset attribute

### PR DESCRIPTION
**Pull request by tafuri**
This is a stab at implementing support for a new vk::offset attribute used to directly specify spirv struct offsets for push constants.

### CODE REVIEW

**Comment by antiagainst** [comment]
Thanks for the PR, @tafuri!

Validation can come later. But would you mind also to add some tests for it? Just need to add a `vk.offset.hlsl` file in the `CodeGenSPIRV` directory and register it in `CodeGenSPIRVTest.cpp`, like https://github.com/Microsoft/DirectXShaderCompiler/pull/637/files. We are using FileCheck style rules.

**Comment by antiagainst** [comment]
The buildbot failure is unrelated to this PR. It's because we are reaching the 1 hour time limit.

**Comment by antiagainst** [comment]
Hi @tafuri, the current implementation is good on its own for non-nested structs. I'm fine to merge it now.

Do you have other changes for this PR, like handling nested structs or adding validation rules? Because I still see "WIP" in the title.

**Comment by tafuri** [comment]
Ah, sorry. At this time no. I had plans to at least add validation and start looking into nested struct. But I did not manage to find any time for that at this point. I will probably do som more work in a subsequent pull request at some point soon.

**Comment by antiagainst** [comment]
Cool. thanks! :)

**Pull request merged**
