### PR TITLE
CMake: Add initial support for MinGW-w64

### PR DESCRIPTION
**Pull request by raedrizqie**

### CODE REVIEW

**Comment by raedrizqie** [comment]
@microsoft-github-policy-service agree

**Review by bogner — APPROVED** [review]
I don’t think we can make any promises that this keeps working without any CI running on it, but these changes all look correct and reasonable to me.

**Review by damyanp — APPROVED** [review]

**Comment by raedrizqie** [comment]
thanks!

**Comment by Biswa96** [comment]
> I don’t think we can make any promises that this keeps working without any CI running on it

There is an ongoing effort to compile this project with mingw-w64 toolchain. Here are some info.

* Help output

```
$ ./UCRT64/bin/dxc --help | head -n 3
OVERVIEW: HLSL Compiler for Windows

Version: libdxcompiler.dll: 1.8 - 1.8.0.10018 (main, 206133c9-dirty)
```

* Dependency list

```
$ ntldd ./UCRT64/bin/dxc.exe | cut -d "=" -f 1
        libgcc_s_seh-1.dll
        KERNEL32.dll
        ole32.dll
        OLEAUT32.dll
        libwinpthread-1.dll
        libstdc++-6.dll
        VERSION.dll
```

The changes in this pull request really helped a lot. Though, many things are need to be done.

**Pull request merged**
