### PR TITLE
Split dxc.exe into a static lib and a driver executable

### PR DESCRIPTION
**Pull request by dmpots**
We have a need to produce a version of dxc.exe that has a few default
command line arguments but otherwise is just the standard dxc executable.
This commit splits dxc.exe into a static lib with all the dxc logic and
a thin wrapper main function that calls into the lib.

The split allows us to link to the dxc lib and pass our own default arguments.

### CODE REVIEW

**Comment by ehsannas** [comment]
Looks like there is a build failure on all platforms when SPIR-V code generation is enabled. I'll post a fix here.

**Comment by ehsannas** [comment]
@dmpots would you give me permission to push to this branch?

**Comment by dmpots** [comment]
@ehsannas yes its fine to push a fix to that branch. Do I need to modify a permission somewhere or can you already push?

**Comment by ehsannas** [comment]
I'm getting "Permission Denied"

**Comment by ehsannas** [comment]
You can give me permission by going to
https://github.com/<you_username>/DirectXShaderCompiler/settings/collaboration
and adding me as a collaborator

**Comment by ehsannas** [comment]
Thanks

**Comment by dmpots** [comment]
Ok, I added you as a collaborator: https://github.com/dmpots/DirectXShaderCompiler/invitations

**Comment by ehsannas** [comment]
Great! Thanks

**Comment by ehsannas** [comment]
Ok, the Windows build and the macOS build pass. Linux build using `clang` also passes. Linux build using `gcc` fails. I'll take a closer.

**Comment by ehsannas** [comment]
These are the errors from `gcc`:
```
[1214/1215] Linking CXX executable bin/dxc-3.7
FAILED: : && /usr/bin/g++-5  -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-unknown-pragmas -fdiagnostics-color -std=c++11 -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-switch -Wno-maybe-uninitialized -Wnon-virtual-dtor -Wno-comment -std=c++11 -fno-common -Woverloaded-virtual -fno-strict-aliasing -g -DDBG -UNDEBUG  -Wl,-allow-shlib-undefined tools/clang/tools/dxc/CMakeFiles/dxc.dir/dxcmain.cpp.o  -o bin/dxc-3.7  -Wl,-rpath,"\$ORIGIN/../lib" lib/libLLVMDxcSupport.a lib/libLLVMDXIL.a lib/libLLVMDxilContainer.a lib/libLLVMHLSL.a lib/libLLVMOption.a lib/libLLVMSupport.a lib/libdxcompiler.so.3.7 lib/libdxclib.a lib/libSPIRV-Tools.a lib/libLLVMDXIL.a lib/libLLVMDxilContainer.a lib/libLLVMHLSL.a lib/libLLVMDxcSupport.a lib/libLLVMBitReader.a lib/libLLVMipa.a lib/libLLVMAnalysis.a lib/libLLVMCore.a lib/libLLVMOption.a lib/libLLVMSupport.a -lrt -ldl -ltinfo -lpthread -lz -lm && :
lib/libdxclib.a(dxc.cpp.o): In function `IDxcBlob::uuidof()':
include/dxc/dxcapi.h:107: undefined reference to `IDxcBlob::IDxcBlob_ID'
...
```
I don't understand why gcc is complaining about this... I'm not able to reproduce it using gcc-7 on my machine. The bots are using gcc-5(?). It could be due to an old gcc issue. I'm inclined to use a newer version of gcc in the Linux buildbot.

**Comment by ehsannas** [comment]
Unfortunately I'm not able to reproduce the gcc build failure locally. I'll try to dig a bit deeper.

**Comment by ehsannas** [comment]
@pow2clk you've wrestled with compiling dxc using gcc more than most 😄. please feel free to provide your insights if any. Thanks :)

**Comment by pow2clk** [comment]
Heh. You caught me lurking. I was already looking into this. 

I am also unable to reproduce the issue locally using GCC5.

FWIW, the decision to use gcc5 on the buildbots was made consciously based on what was widely used on Linux distros. Granted that was a year ago and, full disclosure, I wasn't fully on board with the decision. It doesn't seem to matter anyway.

**Comment by pow2clk** [comment]
Well I've come up with no genius solutions.  As I see it, the various _IDs are defined in dxcapi.cpp, which is linked directly into libdxcompiler.so on my own build. Though I can't see the command on travis, I don't know why it wouldn't do the same. The link command for dxc-3.7 is visible since it's what fails and it shows that libdxcompiler.so is being included.

It might be helpful to get the complete log with commands from the buildbot to try to determine where things are diverging from the local builds or even call `nm`  on dxcapi.cpp.o and libdxcompiler.so after the build completes. I don't believe I have the capability of performing such an experiment, but maybe I'll try setting up a dummy change to iterate on the buildbot anyway.

**Comment by pow2clk** [comment]
Spiffy. I found the solution. It seems the linker used by the build bots is more fussy about the order of files in the link command than the one on my and @ehsannas's systems.

Because it doesn't see the need for the symbols when it first encounters libdxcompiler.so, it ignores them. So when they are needed by subsequent files in the link command, they are not available. By simply reversing the order of dxcompiler and dxclib in the cmake file, the problem is resolved.

@dmpots If you'd like to fix it yourself, take a look at the changes to the cmake file in https://github.com/Microsoft/DirectXShaderCompiler/pull/1959/commits/ec2df8350e77b711f2da346af602e5edf5cb9ff9,  you can ignore the changes to the travis file as they were purely diagnostic. If you'd like me to submit a fix, add me as a collaborator and I'll be happy to. Either way is equally acceptable to me.

**Comment by pow2clk** [comment]
Seems when I closed my dummy pull request,  the links to the travis results are no longer apparent. So here they are explicitly:  https://travis-ci.org/Microsoft/DirectXShaderCompiler/builds/496328699 The apply build failed because I added a change that queried the ld version, which doesn't play nice with apple, but is entirely diagnostic and not necessary for the fix.

**Comment by dmpots** [comment]
Thanks for all the troubleshooting help everybody!

@pow2clk I applied your reordering fix so hopefully the bots will be happy now :) Thanks for finding the solution.

@ehsannas I reverted the move to gcc7 on travis ci since it didn't fix my issue anyway. I don't want to force it in this commit so I'll let you decide if you want to apply it later. Thanks for the help!

**Comment by ehsannas** [comment]
@pow2clk Awesome work! Thanks a lot for putting in the time. Your contributions are always appreciated.

@dmpots Sounds good. Thanks for reverting my travis change.

**Pull request merged**
