### PR TITLE
[SPIR-V] Use KHR_fragment_shader_barycentric for SV_Barycentric semantic

### LINKED ISSUE #644: Support SM6.1 ViewID and barycentrics in SPIR-V
testing new appveyor build with SPIR-V support to check SM6.1 support...
I know I know.. wasn't expecting to work just pointing out..

*Barycentrics:

```
dxc -E main -T ps_6_1 barycentrics1.hlsl -spirv

error: semantic SV_Barycentrics unimplemented yet

```
should be mappable onlty to Vulkan SPIR-V using SPV_AMD_shader_explicit_vertex_parameter perhaps
(https://www.khronos.org/registry/spir-v/extensions/AMD/SPV_AMD_shader_explicit_vertex_parameter.html)

*ViewID: similar story
```
dxc -E main -T ps_6_1 viewid01.hlsl -spirv
error: semantic SV_ViewID unimplemented yet
```
should be mappable to ViewIndex using SPIR-V SPV_KHR_multiview ext: (https://www.khronos.org/registry/spir-v/extensions/KHR/SPV_KHR_multiview.html)
support much better here on desktop (AMD,Intel on Mesa and Nvidia binary drivers Win &Lin)
even there are traces of it on Qualcomm Oreo drivers so should be soon here..

### PR DESCRIPTION
**Pull request by AntonTokarev**
Use KHR_fragment_shader_barycentric instead of AMD_shader_explicit_vertex_parameter for SV_barycentric for cross-vendor compatibility.
Fixes #644

### CODE REVIEW

**Comment by AntonTokarev** [comment]
@microsoft-github-policy-service agree

**Comment by cassiebeckley** [comment]
Hey! Thanks for contributing to the project.

A number of these changes are formatting; were they created by running an automatic code formatter? Also, I haven't reviewed this in detail yet, but is there overlap between this PR and #4638?

**Comment by AntonTokarev** [comment]
> 

Hey. Yes, they were created by clang-format according to the project's .clang-format file rules. Seems that some of the early code weren't formatted properly.

And yes, seems that my changes are overlapped by #4638 . Never mind then, just missed that PR :) I can delete this one

**Comment by cassiebeckley** [comment]
Yeah it's unfortunate, we don't have any CI tests enforcing format so I think it's become somewhat inconsistent. I'll probably try to fix that.

Thanks again for all the work you put into this PR, and feel free to comment on #4638 if you have any questions and feedback.

**Pull request closed without merging**
