### PR TITLE
Add RISC-V 64 bit

### PR DESCRIPTION
**Pull request by FantasqueX**
- Add riscv64 target to config.guess
- Update config-ix.cmake to update config-ix.cmake to support riscv64
- Tested on riscv64

I created a similar PR previously which was closed because we should use the latest GPLv2 version of config.guess. x264 project has the same issue and they solved it by only adding riscv64 support to current config.guess. I think same thing could be done in DirectXShaderCompiler.

Ref:
1. https://github.com/microsoft/DirectXShaderCompiler/pull/4690
2. https://code.videolan.org/videolan/x264/-/merge_requests/121

### CODE REVIEW

**Review by llvm-beanz — APPROVED** [review]
LGTM.

**Comment by llvm-beanz** [comment]
Thank you for understanding and being sensitive to our licensing restrictions.

**Comment by FantasqueX** [comment]
Hi, it's been more than a week since this PR was approved. I wonder when it can be merged. Thanks!

**Comment by python3kgae** [comment]
> Hi, it's been more than a week since this PR was approved. I wonder when it can be merged. Thanks!

Merged.
Happy new year.

**Pull request merged**
