### PR TITLE
[spirv] Emit unsupported error for some intrinsics

### PR DESCRIPTION
**Pull request by antiagainst**
* abort
* GetRenderTargetSampleCount
* GetRenderTargetSamplePosition
* GatherCmpGreen
* GatherCmpBlue
* GatherCmpAlpha
* GetSamplePosition
* CalculateLevelOfDetailUnclamped

### CODE REVIEW

**Comment by jfroy** [comment]
Have bugs been filed for the missing functionality?

**Comment by ehsannas** [comment]
@jfroy you mean filing bugs against Vulkan?

**Comment by antiagainst** [comment]
@jfroy This is just based on our understanding of the spec and reading of related issues on glslang. Haven't filed issues against either SPIR-V or Vulkan. Would like to seek more feedbacks before doing that. :)

**Comment by antiagainst** [comment]
@chaoticbob

**Comment by jfroy** [comment]
@antiagainst Yeah. Programmable sample locations is interesting to me and it seems like an obvious functionality gap. Or I am missing something there?

**Comment by antiagainst** [comment]
@jfroy: Vulkan only support getting the sample position of the **current** sample I think, but HLSL actually allows you to get sample position for any sample. So there is a gap here. See relevant issue on glslang: https://github.com/KhronosGroup/glslang/issues/753.

**Pull request merged**
