### PR TITLE
[spirv] Avoid generating duplicated debug names for images

### PR DESCRIPTION
**Pull request by antiagainst**

### CODE REVIEW

**Comment by antiagainst** [comment]
@ehsannas PTAL

**Comment by ehsannas** [comment]
@antiagainst There are other createXXXType functions in the module builder that also do addDebugName, and this CL only fixes it for Images. I think (as you mentioned in the TODO comment), we should fix this the right way (in addDebugName()).
I think changing 
```cpp
std::vector<DebugName> debugNames;
...
...
  if (!name.empty()) {
    debugNames.emplace_back(targetId, name, memberIndex);
  }
```
to
```cpp
std::set<DebugName> debugNames;
...
...
  if (!name.empty()) {
    debugNames.insert(DebugName(targetId, name, memberIndex));
  }
```
should fix it for all cases.
What do you think?

**Comment by antiagainst** [comment]
@ehsannas: Yep, you've spotted my laziness. ;-P Changed to do de-duplication at `addDebugName()`. Note that I didn't remove some `isRegistered` check to avoid string construction costs. Simple string literals will benefit from the de-duplication in `addDebugName()` right now.

**Comment by antiagainst** [comment]
Only touches SPIR-V files

**Comment by antiagainst** [comment]
Ready to be merged. :)

**Pull request merged**
