### PR TITLE
cherry pick validator fix for SampleCmpBias/Grad to release-1.8

### PR DESCRIPTION
**Pull request by python3kgae**
Cherry pick validator update for SampleCmpBias/Grad.

### CODE REVIEW

**Review by llvm-beanz — COMMENTED** [review]
Can we do these cherry-picks as separate PRs to ensure that the release branch has full history?

**Comment by python3kgae** [comment]
> Can we do these cherry-picks as separate PRs to ensure that the release branch has full history?

Could we merge instead of squash for cherry-pick?

**Comment by tex3d** [comment]
> > Can we do these cherry-picks as separate PRs to ensure that the release branch has full history?
> 
> Could we merge instead of squash for cherry-pick?

I think we need to do one of these two things.  It would be easier to do the merge, since we don't have to build and approve two PRs in a row, with the first having the issue that needed to be fixed by the second.  @llvm-beanz, would that be acceptable to you?

**Comment by hekota** [comment]
Next time can you please go `git cherry-pick -x` which will add the original commit sha to the cherry-pick commit message?

**Review by hekota — APPROVED** [review]
LGMT. It would be nice to add the original commit shas in the PR description.

**Comment by python3kgae** [comment]
> Next time can you please go `git cherry-pick -x` which will add the original commit sha to the cherry-pick commit message?

Fixed.

**Review by pow2clk — APPROVED** [review]

**Pull request merged**
