### PR TITLE
Update required SDK to 10.0.14393.0

### PR DESCRIPTION
**Pull request by marcelolr**

### CODE REVIEW

**Comment by antiagainst** [comment]
I checked my Windows 10 Pro, it seems there is no `dxgi1_4.h` in `Windows Kits\10\Include\10.0.14393.0\shared`? One copy does exist in `Windows Kits\10\Include\10.0.10240.0\shared`. This is also confirmed by [Appveyor buildbot](https://ci.appveyor.com/project/antiagainst/directxshadercompiler/build/5).

**Comment by antiagainst** [comment]
Okey, Installing the latest Win10 SDK solves this problem.

**Comment by marcelolr** [comment]
Did the updated hctstart not complain about this? If you installed/uninstalled a prior version of the SDK, perhaps there was "leftover" state that confused the script, but I'm not sure what that would be ...

**Comment by antiagainst** [comment]
I'm not particularly clear right now. Previously all Win10 SDKs are installed together with Visual Studio. Before I manually installed Win 10 SDK [10.0.14393.795](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk), there is no `dxgi1_4.h` in `Windows Kits\10\Include\10.0.14393.0\shared` (but the directory does exist).  After it appears.

**Pull request merged**
